# Generated by Django 3.1.7 on 2021-06-03 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.CharField(default='0', max_length=20)),
                ('DoctorID', models.CharField(default='0', max_length=20)),
                ('DoctorGmail', models.CharField(max_length=200)),
                ('DoctorUsername', models.CharField(max_length=200)),
                ('PatientUsername', models.CharField(max_length=200)),
                ('PatientGmail', models.CharField(max_length=200)),
                ('Payment', models.CharField(max_length=200)),
                ('SlotID', models.CharField(max_length=20)),
                ('PatientContactNO', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('CardNumber', models.CharField(max_length=200)),
                ('CVCNumber', models.CharField(max_length=200)),
                ('TransectionDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Amount', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='None', max_length=200)),
                ('LastName', models.CharField(default='None', max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=12)),
                ('ContactNO', models.CharField(max_length=11)),
                ('Address', models.CharField(default='NULL', max_length=200)),
                ('Type', models.CharField(default='Patient', max_length=20)),
            ],
        ),
    ]
