# Generated by Django 3.1.7 on 2021-06-03 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorUsername', models.CharField(default='None', max_length=200)),
                ('HolidayName', models.CharField(max_length=200)),
                ('StartDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('EndDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ContactNO',
            field=models.CharField(default='03004347649', max_length=11),
        ),
    ]
