# Generated by Django 3.1.7 on 2021-06-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210603_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.CharField(max_length=20)),
                ('ReportFile', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('LastUpdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('LatestPrescription', models.CharField(default='NULL', max_length=20)),
            ],
        ),
    ]
