# Generated by Django 3.1.7 on 2021-06-10 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
